version: "2"
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: gantry
  errcheck:
    check-blank: false
    check-type-assertions: false
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close
      - (io.Closer).Close

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    # Exclude defer close checks in tests
    - text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck
      path: _test\.go
    # Allow unused parameters (we'll fix manually where needed)
    - text: "unused-parameter"
      linters:
        - revive

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor